server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clients/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**